# The URL the site will be built for
base_url = "https://oteku.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Used in RSS by default
title = "Les carnets d'Oteku"
description = "Je m'appelle Thomas Haesslé, j'écris quelques essais dans ce carnet sur #ReasonML #OCaml #Rust"

# The default language, used in RSS
default_language = "fr"

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "ayu-mirage"
theme = "hyde"
# Whether to generate a RSS feed automatically
generate_rss = true

taxonomies = [
       {name = "tags", rss = true} # each tag will have its own RSS feed
]

tags = ["Rust", "ReasonML", "Ocaml"]

[extra]
# Put all your custom variables here
hyde_theme = "theme-base-0b"
hyde_reverse = true
hyde_links = [
    {url = "https://twitter.com/oteku", name = "Twitter", icon = "icon-twitter"},
    {url = "https://mastodon.social/@oteku", name = "Mastodon"},
    {url = "https://github.com/oteku", name = "Github", icon = "icon-github"},
    {url = "https://www.meetup.com/fr-FR/Lille-FP", name = "LilleFP", icon = "icon-beer"},
]
